Rework executor directories and support local build for components
fepitre/qubes-builderv2 pull request #51
Opened 2022-08-10 15:36 UTC by fepitre

2022-08-19 15:00 UTC, fepitre commented
PipelineRetry

2022-08-20 14:38 UTC, marmarek requested changes

2022-08-20 14:38 UTC, marmarek commented on qubesbuilder/plugins/chroot_deb/__init__.py
> +        if stage != "chroot":
and also, add somewhere tests for init-cache stage

2022-08-20 15:14 UTC, fepitre commented on qubesbuilder/plugins/chroot_deb/__init__.py
> +        if stage != "chroot":
Yes this is what I'm already testing here: https://github.com/fepitre/qubes-builderv2/pull/52 with fix notably of wrong stage name.

2022-08-20 19:01 UTC, marmarek approved these changes

2022-08-20 23:19 UTC, merged